name: sshman # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: SSH Session Manager CLI # 79 char long summary
description: |
  SSH Session Manager that store your ssh sessions and password and 
  make easy to reconnect them

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  sshman:
    # See 'snapcraft plugins'
    plugin: go
    source: https://github.com/bakyazi/sshman.git
    override-pull: snapcraftctl pull

apps:
  sshman:
    command: bin/sshman
    plugs:
      - network